exports.home=(req,res)=>{
    res.render('index')
}
exports.registers=(req,res)=>{
    res.render('signup')
}
exports.userdetail=(req,res)=>{
    res.render('userdetails')
}
exports.update=(req,res)=>{
    res.render('update')
}
exports.admin=(req,res)=>{
    res.render('admin')
}